name: demo workflow01

on:
  push:
  pull_request:

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: sleep
        run: sleep 5
        
      - name: Install cowsay
        run: |
          chmod +x install-cowsay.sh
          ./install-cowsay.sh