name: demo workflow01

on: [push, pull_request]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo 
          uses: actions/checkout@v7
          
        - name: install Cow says
          run: | 
            sudo apt-get install cowsay -y
            cowsay -f lion "run fast" >> lion.txt
            grep -i "lion" lion.txt
            cat lion.txt
            ls -ltra 
