name: Exploring filters

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'releases/**'
  pull_request:
    types: [opened, reopened, closed]
    branches: 
      - main
      - testing-events

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: sleep
        run: sleep 2

      - name: Install cowsay
        run: echo this workflow/job/step is executed for event type ${{github.event_name}}